name: poke

version: 1.7.1+71

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_launcher_icons: ^0.14.3
  cupertino_icons: ^1.0.8
  loading_animation_widget: ^1.3.0

  provider: ^6.1.5

  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3

  http: ^1.1.2
  http_parser: ^4.1.2

  image_picker: 1.0.7
  extended_image: ^10.0.1
  flutter_svg: ^2.1.0

  better_player_plus: ^1.0.8

  firebase_core: ^3.13.1
  firebase_messaging: ^15.2.6
  no_screenshot: ^0.3.1

  geolocator: ^14.0.1
  geocoding: ^4.0.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path_android: 'images/icon_and.png'
  image_path_ios: 'images/icon_ios.jpg'
